// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Metric.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Metric_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Metric_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Metric_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Metric_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Metric_2eproto;
namespace apm {
class Metric;
struct MetricDefaultTypeInternal;
extern MetricDefaultTypeInternal _Metric_default_instance_;
}  // namespace apm
PROTOBUF_NAMESPACE_OPEN
template<> ::apm::Metric* Arena::CreateMaybeMessage<::apm::Metric>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apm {

// ===================================================================

class Metric final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apm.Metric) */ {
 public:
  inline Metric() : Metric(nullptr) {}
  ~Metric() override;
  explicit PROTOBUF_CONSTEXPR Metric(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Metric(const Metric& from);
  Metric(Metric&& from) noexcept
    : Metric() {
    *this = ::std::move(from);
  }

  inline Metric& operator=(const Metric& from) {
    CopyFrom(from);
    return *this;
  }
  inline Metric& operator=(Metric&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Metric& default_instance() {
    return *internal_default_instance();
  }
  static inline const Metric* internal_default_instance() {
    return reinterpret_cast<const Metric*>(
               &_Metric_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Metric& a, Metric& b) {
    a.Swap(&b);
  }
  inline void Swap(Metric* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Metric* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Metric* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Metric>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Metric& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Metric& from) {
    Metric::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Metric* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apm.Metric";
  }
  protected:
  explicit Metric(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCpuUsagePercentFieldNumber = 1,
    kMemUsedBytesFieldNumber = 2,
    kMemTotalBytesFieldNumber = 3,
    kDiskUsedBytesFieldNumber = 4,
    kDiskTotalBytesFieldNumber = 5,
    kNetRxBytesPerSecFieldNumber = 6,
    kNetTxBytesPerSecFieldNumber = 7,
    kTcpRttUsFieldNumber = 8,
    kTcpRttVarUsFieldNumber = 9,
    kTcpRetransmitsFieldNumber = 10,
    kTcpTotalRetransFieldNumber = 11,
    kTcpSndCwndFieldNumber = 12,
  };
  // double cpu_usage_percent = 1;
  void clear_cpu_usage_percent();
  double cpu_usage_percent() const;
  void set_cpu_usage_percent(double value);
  private:
  double _internal_cpu_usage_percent() const;
  void _internal_set_cpu_usage_percent(double value);
  public:

  // uint64 mem_used_bytes = 2;
  void clear_mem_used_bytes();
  uint64_t mem_used_bytes() const;
  void set_mem_used_bytes(uint64_t value);
  private:
  uint64_t _internal_mem_used_bytes() const;
  void _internal_set_mem_used_bytes(uint64_t value);
  public:

  // uint64 mem_total_bytes = 3;
  void clear_mem_total_bytes();
  uint64_t mem_total_bytes() const;
  void set_mem_total_bytes(uint64_t value);
  private:
  uint64_t _internal_mem_total_bytes() const;
  void _internal_set_mem_total_bytes(uint64_t value);
  public:

  // uint64 disk_used_bytes = 4;
  void clear_disk_used_bytes();
  uint64_t disk_used_bytes() const;
  void set_disk_used_bytes(uint64_t value);
  private:
  uint64_t _internal_disk_used_bytes() const;
  void _internal_set_disk_used_bytes(uint64_t value);
  public:

  // uint64 disk_total_bytes = 5;
  void clear_disk_total_bytes();
  uint64_t disk_total_bytes() const;
  void set_disk_total_bytes(uint64_t value);
  private:
  uint64_t _internal_disk_total_bytes() const;
  void _internal_set_disk_total_bytes(uint64_t value);
  public:

  // uint64 net_rx_bytes_per_sec = 6;
  void clear_net_rx_bytes_per_sec();
  uint64_t net_rx_bytes_per_sec() const;
  void set_net_rx_bytes_per_sec(uint64_t value);
  private:
  uint64_t _internal_net_rx_bytes_per_sec() const;
  void _internal_set_net_rx_bytes_per_sec(uint64_t value);
  public:

  // uint64 net_tx_bytes_per_sec = 7;
  void clear_net_tx_bytes_per_sec();
  uint64_t net_tx_bytes_per_sec() const;
  void set_net_tx_bytes_per_sec(uint64_t value);
  private:
  uint64_t _internal_net_tx_bytes_per_sec() const;
  void _internal_set_net_tx_bytes_per_sec(uint64_t value);
  public:

  // uint32 tcp_rtt_us = 8;
  void clear_tcp_rtt_us();
  uint32_t tcp_rtt_us() const;
  void set_tcp_rtt_us(uint32_t value);
  private:
  uint32_t _internal_tcp_rtt_us() const;
  void _internal_set_tcp_rtt_us(uint32_t value);
  public:

  // uint32 tcp_rtt_var_us = 9;
  void clear_tcp_rtt_var_us();
  uint32_t tcp_rtt_var_us() const;
  void set_tcp_rtt_var_us(uint32_t value);
  private:
  uint32_t _internal_tcp_rtt_var_us() const;
  void _internal_set_tcp_rtt_var_us(uint32_t value);
  public:

  // uint32 tcp_retransmits = 10;
  void clear_tcp_retransmits();
  uint32_t tcp_retransmits() const;
  void set_tcp_retransmits(uint32_t value);
  private:
  uint32_t _internal_tcp_retransmits() const;
  void _internal_set_tcp_retransmits(uint32_t value);
  public:

  // uint32 tcp_total_retrans = 11;
  void clear_tcp_total_retrans();
  uint32_t tcp_total_retrans() const;
  void set_tcp_total_retrans(uint32_t value);
  private:
  uint32_t _internal_tcp_total_retrans() const;
  void _internal_set_tcp_total_retrans(uint32_t value);
  public:

  // uint32 tcp_snd_cwnd = 12;
  void clear_tcp_snd_cwnd();
  uint32_t tcp_snd_cwnd() const;
  void set_tcp_snd_cwnd(uint32_t value);
  private:
  uint32_t _internal_tcp_snd_cwnd() const;
  void _internal_set_tcp_snd_cwnd(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:apm.Metric)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double cpu_usage_percent_;
    uint64_t mem_used_bytes_;
    uint64_t mem_total_bytes_;
    uint64_t disk_used_bytes_;
    uint64_t disk_total_bytes_;
    uint64_t net_rx_bytes_per_sec_;
    uint64_t net_tx_bytes_per_sec_;
    uint32_t tcp_rtt_us_;
    uint32_t tcp_rtt_var_us_;
    uint32_t tcp_retransmits_;
    uint32_t tcp_total_retrans_;
    uint32_t tcp_snd_cwnd_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Metric_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Metric

// double cpu_usage_percent = 1;
inline void Metric::clear_cpu_usage_percent() {
  _impl_.cpu_usage_percent_ = 0;
}
inline double Metric::_internal_cpu_usage_percent() const {
  return _impl_.cpu_usage_percent_;
}
inline double Metric::cpu_usage_percent() const {
  // @@protoc_insertion_point(field_get:apm.Metric.cpu_usage_percent)
  return _internal_cpu_usage_percent();
}
inline void Metric::_internal_set_cpu_usage_percent(double value) {
  
  _impl_.cpu_usage_percent_ = value;
}
inline void Metric::set_cpu_usage_percent(double value) {
  _internal_set_cpu_usage_percent(value);
  // @@protoc_insertion_point(field_set:apm.Metric.cpu_usage_percent)
}

// uint64 mem_used_bytes = 2;
inline void Metric::clear_mem_used_bytes() {
  _impl_.mem_used_bytes_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_mem_used_bytes() const {
  return _impl_.mem_used_bytes_;
}
inline uint64_t Metric::mem_used_bytes() const {
  // @@protoc_insertion_point(field_get:apm.Metric.mem_used_bytes)
  return _internal_mem_used_bytes();
}
inline void Metric::_internal_set_mem_used_bytes(uint64_t value) {
  
  _impl_.mem_used_bytes_ = value;
}
inline void Metric::set_mem_used_bytes(uint64_t value) {
  _internal_set_mem_used_bytes(value);
  // @@protoc_insertion_point(field_set:apm.Metric.mem_used_bytes)
}

// uint64 mem_total_bytes = 3;
inline void Metric::clear_mem_total_bytes() {
  _impl_.mem_total_bytes_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_mem_total_bytes() const {
  return _impl_.mem_total_bytes_;
}
inline uint64_t Metric::mem_total_bytes() const {
  // @@protoc_insertion_point(field_get:apm.Metric.mem_total_bytes)
  return _internal_mem_total_bytes();
}
inline void Metric::_internal_set_mem_total_bytes(uint64_t value) {
  
  _impl_.mem_total_bytes_ = value;
}
inline void Metric::set_mem_total_bytes(uint64_t value) {
  _internal_set_mem_total_bytes(value);
  // @@protoc_insertion_point(field_set:apm.Metric.mem_total_bytes)
}

// uint64 disk_used_bytes = 4;
inline void Metric::clear_disk_used_bytes() {
  _impl_.disk_used_bytes_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_disk_used_bytes() const {
  return _impl_.disk_used_bytes_;
}
inline uint64_t Metric::disk_used_bytes() const {
  // @@protoc_insertion_point(field_get:apm.Metric.disk_used_bytes)
  return _internal_disk_used_bytes();
}
inline void Metric::_internal_set_disk_used_bytes(uint64_t value) {
  
  _impl_.disk_used_bytes_ = value;
}
inline void Metric::set_disk_used_bytes(uint64_t value) {
  _internal_set_disk_used_bytes(value);
  // @@protoc_insertion_point(field_set:apm.Metric.disk_used_bytes)
}

// uint64 disk_total_bytes = 5;
inline void Metric::clear_disk_total_bytes() {
  _impl_.disk_total_bytes_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_disk_total_bytes() const {
  return _impl_.disk_total_bytes_;
}
inline uint64_t Metric::disk_total_bytes() const {
  // @@protoc_insertion_point(field_get:apm.Metric.disk_total_bytes)
  return _internal_disk_total_bytes();
}
inline void Metric::_internal_set_disk_total_bytes(uint64_t value) {
  
  _impl_.disk_total_bytes_ = value;
}
inline void Metric::set_disk_total_bytes(uint64_t value) {
  _internal_set_disk_total_bytes(value);
  // @@protoc_insertion_point(field_set:apm.Metric.disk_total_bytes)
}

// uint64 net_rx_bytes_per_sec = 6;
inline void Metric::clear_net_rx_bytes_per_sec() {
  _impl_.net_rx_bytes_per_sec_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_net_rx_bytes_per_sec() const {
  return _impl_.net_rx_bytes_per_sec_;
}
inline uint64_t Metric::net_rx_bytes_per_sec() const {
  // @@protoc_insertion_point(field_get:apm.Metric.net_rx_bytes_per_sec)
  return _internal_net_rx_bytes_per_sec();
}
inline void Metric::_internal_set_net_rx_bytes_per_sec(uint64_t value) {
  
  _impl_.net_rx_bytes_per_sec_ = value;
}
inline void Metric::set_net_rx_bytes_per_sec(uint64_t value) {
  _internal_set_net_rx_bytes_per_sec(value);
  // @@protoc_insertion_point(field_set:apm.Metric.net_rx_bytes_per_sec)
}

// uint64 net_tx_bytes_per_sec = 7;
inline void Metric::clear_net_tx_bytes_per_sec() {
  _impl_.net_tx_bytes_per_sec_ = uint64_t{0u};
}
inline uint64_t Metric::_internal_net_tx_bytes_per_sec() const {
  return _impl_.net_tx_bytes_per_sec_;
}
inline uint64_t Metric::net_tx_bytes_per_sec() const {
  // @@protoc_insertion_point(field_get:apm.Metric.net_tx_bytes_per_sec)
  return _internal_net_tx_bytes_per_sec();
}
inline void Metric::_internal_set_net_tx_bytes_per_sec(uint64_t value) {
  
  _impl_.net_tx_bytes_per_sec_ = value;
}
inline void Metric::set_net_tx_bytes_per_sec(uint64_t value) {
  _internal_set_net_tx_bytes_per_sec(value);
  // @@protoc_insertion_point(field_set:apm.Metric.net_tx_bytes_per_sec)
}

// uint32 tcp_rtt_us = 8;
inline void Metric::clear_tcp_rtt_us() {
  _impl_.tcp_rtt_us_ = 0u;
}
inline uint32_t Metric::_internal_tcp_rtt_us() const {
  return _impl_.tcp_rtt_us_;
}
inline uint32_t Metric::tcp_rtt_us() const {
  // @@protoc_insertion_point(field_get:apm.Metric.tcp_rtt_us)
  return _internal_tcp_rtt_us();
}
inline void Metric::_internal_set_tcp_rtt_us(uint32_t value) {
  
  _impl_.tcp_rtt_us_ = value;
}
inline void Metric::set_tcp_rtt_us(uint32_t value) {
  _internal_set_tcp_rtt_us(value);
  // @@protoc_insertion_point(field_set:apm.Metric.tcp_rtt_us)
}

// uint32 tcp_rtt_var_us = 9;
inline void Metric::clear_tcp_rtt_var_us() {
  _impl_.tcp_rtt_var_us_ = 0u;
}
inline uint32_t Metric::_internal_tcp_rtt_var_us() const {
  return _impl_.tcp_rtt_var_us_;
}
inline uint32_t Metric::tcp_rtt_var_us() const {
  // @@protoc_insertion_point(field_get:apm.Metric.tcp_rtt_var_us)
  return _internal_tcp_rtt_var_us();
}
inline void Metric::_internal_set_tcp_rtt_var_us(uint32_t value) {
  
  _impl_.tcp_rtt_var_us_ = value;
}
inline void Metric::set_tcp_rtt_var_us(uint32_t value) {
  _internal_set_tcp_rtt_var_us(value);
  // @@protoc_insertion_point(field_set:apm.Metric.tcp_rtt_var_us)
}

// uint32 tcp_retransmits = 10;
inline void Metric::clear_tcp_retransmits() {
  _impl_.tcp_retransmits_ = 0u;
}
inline uint32_t Metric::_internal_tcp_retransmits() const {
  return _impl_.tcp_retransmits_;
}
inline uint32_t Metric::tcp_retransmits() const {
  // @@protoc_insertion_point(field_get:apm.Metric.tcp_retransmits)
  return _internal_tcp_retransmits();
}
inline void Metric::_internal_set_tcp_retransmits(uint32_t value) {
  
  _impl_.tcp_retransmits_ = value;
}
inline void Metric::set_tcp_retransmits(uint32_t value) {
  _internal_set_tcp_retransmits(value);
  // @@protoc_insertion_point(field_set:apm.Metric.tcp_retransmits)
}

// uint32 tcp_total_retrans = 11;
inline void Metric::clear_tcp_total_retrans() {
  _impl_.tcp_total_retrans_ = 0u;
}
inline uint32_t Metric::_internal_tcp_total_retrans() const {
  return _impl_.tcp_total_retrans_;
}
inline uint32_t Metric::tcp_total_retrans() const {
  // @@protoc_insertion_point(field_get:apm.Metric.tcp_total_retrans)
  return _internal_tcp_total_retrans();
}
inline void Metric::_internal_set_tcp_total_retrans(uint32_t value) {
  
  _impl_.tcp_total_retrans_ = value;
}
inline void Metric::set_tcp_total_retrans(uint32_t value) {
  _internal_set_tcp_total_retrans(value);
  // @@protoc_insertion_point(field_set:apm.Metric.tcp_total_retrans)
}

// uint32 tcp_snd_cwnd = 12;
inline void Metric::clear_tcp_snd_cwnd() {
  _impl_.tcp_snd_cwnd_ = 0u;
}
inline uint32_t Metric::_internal_tcp_snd_cwnd() const {
  return _impl_.tcp_snd_cwnd_;
}
inline uint32_t Metric::tcp_snd_cwnd() const {
  // @@protoc_insertion_point(field_get:apm.Metric.tcp_snd_cwnd)
  return _internal_tcp_snd_cwnd();
}
inline void Metric::_internal_set_tcp_snd_cwnd(uint32_t value) {
  
  _impl_.tcp_snd_cwnd_ = value;
}
inline void Metric::set_tcp_snd_cwnd(uint32_t value) {
  _internal_set_tcp_snd_cwnd(value);
  // @@protoc_insertion_point(field_set:apm.Metric.tcp_snd_cwnd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace apm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Metric_2eproto
