<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\ApmConsole.Contracts\ApmConsole.Contracts.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <Target Name="CopyToHostModules" AfterTargets="Build">
    <ItemGroup>
      <OutputFiles Include="$(TargetDir)**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(OutputFiles)"
          DestinationFolder="$(MSBuildThisFileDirectory)..\..\..\ApmConsole.Host\bin\$(Configuration)\net8.0\Modules\Game\%(RecursiveDir)" />
  </Target>

</Project>
